**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

# Checkpoints

In [ ]:
from itertools import combinations
def generate_two_combs(alist):
  return combinations(alist, 2)

res = generate_two_combs(["A", "B", "C"])
for val in list(res):
  print(val)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
from itertools import cycle
def cycle_print(alist, stop_point = 10):
  cnt = 0
  for val in cycle(alist):
    print(val)
    cnt += 1

    if cnt == 10:
      return

cycle_print(["Python", "is", "fun"])


Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:

*   List item

*   List item
*   List item


*   List item


Use the `glob` module to list all python (.py) files in your current working directory.




In [ ]:
import glob

python_files = glob.glob('*.py')
# print(python_files, 'files')
for fle in python_files:
  print(fle)


[] files


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup("<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>", 'html.parser')
p_tag = soup.find('p')

print(p_tag.text)




AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [ ]:
import re
html_text = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
new_html_text = re.sub(r'\bAI\b', "Artificial Intelligence", html_text)
print(new_html_text)

<html><body><div class='main'><h1>Welcome to Artificial Intelligence</h1><p>Artificial Intelligence is transforming the world</p></div></body></html>


**CP6**: Create a numpy array of 10 zeros.

In [ ]:
import numpy as np

nums = np.zeros(10)
print(nums)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**CP7** Create a numpy array of the integers from 10 to 49.

In [ ]:
import numpy as np

nums = np.random.randint(10, 50, 10)
print(nums)

[20 38 21 28 44 37 28 15 18 10]


**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [ ]:
import numpy as np

nums_grid = np.random.randint(0, 9, (3, 3))
print(nums_grid)

[[4 2 5]
 [2 8 3]
 [2 0 1]]


**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [ ]:
"""
  I believe having a large amount of data helps in two major ways - to build an accurate model and to avoid the problem of overfitting.
  By accurate i mean the more we train the model on different data, the model will see different patterns and learn to recognise variations
  that might happen in the real world. It also helps to avoid overfitting because more data creates generalisation for unseen data.

  The concept of "large" data is relative and depends on the context. It is often assessed based on factors like the number 
  of samples, the dimensionality of the data, and the diversity and representativeness of the data with respect to the problem at
  hand. Ultimately, the goal is to have a dataset that is large enough to capture the underlying patterns and variations required 
  for effective model training and generalization.
"""

'\n  I believe having a large amount of data helps in two major ways - to build an accurate model and to avoid the problem of overfitting.\n  By accurate i mean the more we train the model on different data, the model will see different patterns and learn to recognise variations  \n'

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [ ]:
"""
  1, Cyber attacks : ai can be used to plan an effective and powerful cyber attacks. Because LLMs are trained
  on the whole internet, they are kind of all knowing. if they are not fine tuned well an attacker might use them
  to create a powerful and efficient attacks on different systems.

  solution: fine tuning the model, to not respond to such kind of prompts.

  2, Generation of fake news: AI specially LLMs like chatgpt can be used to create realistic fake news.
  which can be very dangerous anywhere, i can create chaos and disorder in a country.

  solution: Fact-checking and verification: Developing AI-based tools and techniques to detect
  and debunk fake news, misinformation, and manipulated content.

"""