Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [ ]:
NAME = "Daniel Wossen"

---

# Q3

Let us start by importing `Numpy`.

In [2]:
def import_numpy():
    import numpy as np

In [3]:
import_numpy()

Create an array of 10 zeros

In [8]:
import numpy as np
def create_zeros():
    """Create an array of 10 zeros."""
    return np.zeros(10)


In [9]:
"""Check that create_zeros returns the correct output"""
create_zeros()


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [10]:
def create_ones():
    """Create an array of 10 ones."""
    return np.ones(10)


In [11]:
"""Check that create_ones returns the correct output"""
create_ones()


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [12]:
def create_fives():
    """Create an array of 10 fives."""
    return np.ones(10) * 5


In [13]:
"""Check that create_fives returns the correct output"""

create_fives()


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of the integers from 10 to 50

In [16]:
def create_array_10_to_50():
    """Create an array of the integers from 10 to 50."""
    return np.arange(10, 51)


In [17]:
"""Check that create_array_10_to_50 returns the correct output"""
create_array_10_to_50()


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
def create_matrix_0_to_8():
    """Create a 3x3 matrix with values ranging from 0 to 8."""
    return np.arange(0, 9).reshape(3, 3)    


In [21]:
"""Check that create_matrix_0_to_8 returns the correct output"""
create_matrix_0_to_8()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Use NumPy to generate a random number between 0 and 1

In [24]:
def create_random_number():
    """Generate a random number between 0 and 1."""
    return np.random.random()


In [37]:
"""Check that create_random_number returns the correct output"""
create_random_number()

0.06941017098693691

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [40]:
def create_random_numbers():
    """Generate an array of 25 random numbers from a standard normal distribution."""
    return np.random.rand(25)


In [41]:
"""Check that create_random_numbers returns the correct output"""
create_random_numbers()

array([0.29136287, 0.89098345, 0.3901109 , 0.6489079 , 0.30215466,
       0.85764197, 0.72513772, 0.61372199, 0.066465  , 0.19497894,
       0.44324477, 0.55625839, 0.8780399 , 0.09229352, 0.88716732,
       0.40153985, 0.19938287, 0.3367786 , 0.87319442, 0.09626434,
       0.98674956, 0.13093883, 0.66519958, 0.96983962, 0.10161285])

q) Write a function that accepts a numpy array and a threshold value, and returns a new array that contains only the elements of the input array that are greater than the threshold. 


In [50]:
def select_greater_than(array, threshold):
    """Return a new array that contains only the elements of the input array that are greater than the threshold."""
    return np.where(array > threshold)

In [51]:
"""Check that select_greater_than returns the correct output for several inputs"""
select_greater_than(np.array([1, 2, 3, 4, 5, 6]), 3)

(array([3, 4, 5], dtype=int64),)

q) Write a function that accepts a numpy array and a scalar value, and returns a new array that is the result of adding the scalar value to each element of the input array (using broadcasting).


In [53]:
def add_scalar(array, scalar):
    """Return a new array that is the result of adding the scalar value to each element of the input array."""
    return array + scalar


In [56]:
"""Check that add_scalar returns the correct output for several inputs"""
add_scalar(np.array([1,2,3]), 2)

array([3, 4, 5])